import { promises as fs } from 'node:fs';
import path from 'node:path';
import {
  fromRoot,
  pathExists,
  readJson,
  readYaml,
  requestedFeature,
} from '../prototype-cli/project.mjs';
import { markdownSectionBody } from '../prototype-cli/intake-policy.mjs';
import { resolveSurfaceContext } from '../prototype-cli/surface-policy.mjs';
import { validateComponentContracts } from '../design-library/component-contracts.mjs';

/**
 * One generated page the generator reads instead of the whole product folder.
 *
 * It carries the contract (states, actions, acceptance), the resolved surface with
 * presence, every role's reuse resolution, the public API of each shared component
 * the feature imports, the canonical decisions, open design gaps and the i18n keys.
 * It does not carry the PRD, the validation selectors, the review log or the
 * research brief: the first generation still reads the PRD and validation.yaml, and
 * a revise reads only the delta the PM feedback touches.
 */
const feature = requestedFeature();
if (!feature) throw new Error('Usage: feature:digest -- <feature>');

const productRoot = path.join('features', feature, 'product');
const read = (file) => fromRoot(productRoot, file);
const contract = await readYaml(path.join(productRoot, 'prototype.contract.yaml'));
const surfaceIntent = await readYaml(path.join(productRoot, 'surface-intent.yaml'));
const gaps = await readYaml(path.join('features', feature, 'design', 'design-gaps.yaml'));
const decisions = await fs.readFile(read('decisions.md'), 'utf8');
const dictionary = (await pathExists(read('i18n.json')))
  ? await readJson(path.join(productRoot, 'i18n.json'))
  : null;
const surfaceResult = await resolveSurfaceContext(feature);
const surface = surfaceResult.context;
const { contracts } = await validateComponentContracts();
const catalogue = new Map(contracts.map(({ contract: item }) => [item.id, item]));

const presenceOf = (group, id) => surface?.presence?.[group]?.[id]?.presence ?? 'at-rest';
const presenceNote = (group, id) => {
  const entry = surface?.presence?.[group]?.[id];
  if (!entry) return '';
  return [entry.via ? 'via ' + entry.via : '', entry.reason ? entry.reason : '']
    .filter(Boolean)
    .join('; ');
};

const lines = [
  '<!-- GENERATED by npm run feature:digest -- ' + feature + '. Do not edit; regenerate. -->',
  '# ' + contract.feature.title + ' — generation digest',
  '',
  '- Feature: `' + feature + '`',
  '- Entry route: `' + contract.feature.entryRoute + '`',
  '- Intake status: ' + contract.feature.intakeStatus,
  '- Generated at: ' + new Date().toISOString(),
  '- Read next: `product/prd.md` for behaviour rules, `product/validation.yaml` for selectors. Do not read `decisions.md` review log or the research brief for generation.',
  '',
  '## Surface',
  '',
  '- Strategy: `' + surfaceIntent.strategy + '`',
];

if (surface) {
  if (surface.primaryPack) {
    lines.push('- Primary pack: `' + surface.primaryPack.id + '@' + surface.primaryPack.version + '`');
  }
  for (const pack of surface.borrowedPacks ?? []) {
    lines.push('- Borrowed: `' + pack.id + '@' + pack.version + '` roles ' + pack.roles.join(', '));
  }
  lines.push('', '| Zone | Presence | Note |', '|---|---|---|');
  for (const zone of surface.requiredZones) {
    lines.push('| `' + zone + '` | ' + presenceOf('zones', zone) + ' | ' + presenceNote('zones', zone) + ' |');
  }
  lines.push('', 'Emit `data-surface-zone` for every zone; only `at-rest` zones are asserted on the entry route.');
} else {
  lines.push('- Surface context could not be resolved:', ...surfaceResult.errors.map((error) => '  - ' + error));
}

lines.push('', '## Component roles', '', '| Role | Resolution | Component | Presence | Note |', '|---|---|---|---|---|');
const reuseByRole = new Map((surfaceIntent.componentReuse ?? []).map((entry) => [entry.role, entry]));
for (const role of surface?.requiredComponentRoles ?? surfaceIntent.layoutIntent.componentRoles) {
  const reuse = reuseByRole.get(role);
  lines.push(
    '| `' + role + '` | ' + (reuse?.resolution ?? 'pack-slot') + ' | ' +
      (reuse?.component ? '`' + reuse.component + '`' : '') + ' | ' +
      presenceOf('componentRoles', role) + ' | ' + presenceNote('componentRoles', role) + ' |',
  );
}
lines.push('', 'Emit `data-component-role` for every role. A role resolved as `existing-component` must be satisfied by importing that component.');

const imported = [...new Set((surfaceIntent.componentReuse ?? [])
  .filter((entry) => entry.resolution === 'existing-component' && entry.component)
  .map((entry) => entry.component))].sort();
lines.push('', '## Shared component APIs', '');
for (const id of imported) {
  const component = catalogue.get(id);
  if (!component) {
    lines.push('- `' + id + '`: not in the catalogue (validate:inputs will fail)');
    continue;
  }
  const props = (component.publicApi?.props ?? [])
    .map((prop) => prop.name + (prop.required ? '*' : '') + (prop.values ? '<' + prop.values.join('|') + '>' : ''))
    .join(', ');
  lines.push(
    '- `' + id + '` — import `' + component.implementation.importPath + '`; props: ' + (props || 'none') +
      '; states: ' + (component.publicApi?.states ?? []).join(', '),
  );
}
if (imported.length === 0) lines.push('- none');

lines.push('', '## States', '');
for (const state of contract.states) lines.push('- `' + state.id + '` — ' + state.description);
lines.push('', '## Actions', '');
for (const action of contract.actions) {
  lines.push('- `' + action.id + '`: ' + action.from + ' → ' + action.to + ' — ' + action.event);
}
lines.push('', '## Acceptance', '');
for (const criterion of contract.acceptance) {
  lines.push('- `' + criterion.id + '` — given ' + criterion.given + '; when ' + criterion.when + '; then ' + criterion.then);
}

lines.push('', '## Canonical decisions', '', markdownSectionBody(decisions, 'Decisions').trim());

const openGaps = (gaps.gaps ?? []).filter((gap) => gap.status !== 'resolved');
lines.push('', '## Open design gaps', '');
for (const gap of openGaps) {
  lines.push('- `' + gap.id + '` (' + gap.status + ') — ' + String(gap.description).slice(0, 200));
}
if (openGaps.length === 0) lines.push('- none');

lines.push('', '## i18n keys', '');
if (dictionary) {
  lines.push('Use `t(\'key\')` from `platform/runtime/i18n.js`; never add a key the dictionary does not declare.', '');
  for (const [key, entry] of Object.entries(dictionary.keys ?? {})) {
    lines.push('- `' + key + '`' + (entry.status === 'planned' ? ' (planned)' : '') + ' — ' + String(entry.value).slice(0, 60));
  }
} else {
  lines.push('- product/i18n.json does not exist yet; every user-facing string needs a key before generation.');
}

const outputRoot = fromRoot('.collab-cache', 'features', feature);
await fs.mkdir(outputRoot, { recursive: true });
const outputPath = path.join(outputRoot, 'digest.md');
await fs.writeFile(outputPath, lines.join('\n') + '\n');
process.stdout.write(
  '[digest] WROTE ' + path.relative(fromRoot(), outputPath).split(path.sep).join('/') +
    ' (' + lines.length + ' lines)\n',
);
