import {
  moduleTypes,
  sodTypes,
  videoTypes4ModuleBanner,
} from './moduleTypes.js';

// Product URLs mapping
export const productUrls = {
  [moduleTypes.enhance]: '/photo-enhance',
  [moduleTypes.enhanceBatch]: '/photo-enhance',
  [moduleTypes.dehazePhoto]: '/photo-enhance',
  [moduleTypes.shaprenImage]: '/photo-enhance',
  [moduleTypes.unblurImage]: '/photo-enhance',
  [moduleTypes.objRemoval]: '/object-removal',
  [moduleTypes.genFill]: '/object-removal',
  [moduleTypes.watermarkRemover]: '/object-removal',
  [moduleTypes.sod]: {
    [sodTypes.remove]: '/remove-background',
    [sodTypes.blur]: '/blur-background',
    [sodTypes.change]: '/change-background',
  },
  [moduleTypes.colorize]: '/colorize',
  [moduleTypes.oldPhotoRestoration]: '/colorize',
  [moduleTypes.lighting]: '/ai-lighting',
  [moduleTypes.avatar]: '/avatar',
  [moduleTypes.avatarPet]: '/avatar',
  [moduleTypes.avtV3Art]: '/avatar',
  [moduleTypes.txt2Img]: '/ai-art-generator',
  [moduleTypes.hairStyle]: '/ai-hairstyle-generator',
  [moduleTypes.hairTransfer]: '/ai-hairstyle-generator',
  [moduleTypes.hairBang]: '/bangs-filter',
  [moduleTypes.hairExt]: '/before-and-after-hair-extensions',
  [moduleTypes.hairVol]: '/add-hair-to-photo-with-ai',
  [moduleTypes.resizeImage]: '/resize-image',
  [moduleTypes.cropPhoto]: '/crop-photo',
  [moduleTypes.flipAndRotateImage]: '/flip-and-rotate-image',
  [moduleTypes.outPaint]: '/ai-image-extender',
  [moduleTypes.objReplace]: '/ai-replace',
  [moduleTypes.avtV3Img]: '/ai-portrait-generator',
  [moduleTypes.headshot]: '/ai-headshot-generator',
  [moduleTypes.muTransfer]: '/facial-makeup-transfer-filter',
  [moduleTypes.colorCorrection]: '/color-correction',
  [moduleTypes.videoSr]: '/video-enhancer-ai',
  [moduleTypes.faceShapeDetector]: '/face-shape-detector',
  [moduleTypes.faceSwap]: '/face-swap',
  [moduleTypes.aiVideoFilters]: '/ai-video-filters',
  [moduleTypes.faceSwapVid]: '/video-face-swap',
  [moduleTypes.aiPortrait]: '/ai-portrait',
  [moduleTypes.img2Vid]: '/ai-video-generator',
  [moduleTypes.img2VidStd]: '/ai-video-generator',
  [moduleTypes.img2VidPro]: '/ai-video-generator',
  [moduleTypes.viduVidTmpl]: '/ai-video-generator',
  [moduleTypes.makeup]: '/ai-makeup',
  [moduleTypes.imageConverter]: '/image-converter',
  [moduleTypes.imageConverterBatch]: '/image-converter',
  [moduleTypes.adjustLightColor]: '/adjust-light-n-color',
  [moduleTypes.hairWavy]: '/hair-wavy',
  [moduleTypes.skinAnalysis]: '/ai-skin-analysis',
  [moduleTypes.faceReshape]: '/face-reshape',
  [moduleTypes.faceRetouch]: '/products/face-retouch',
  [moduleTypes.aiClothes]: '/ai-clothes',
  [moduleTypes.aiFabric]: '/ai-fabric',
  [moduleTypes.edit]: '/edit',
  [moduleTypes.beardFilter]: '/products/beard-filter',
  [moduleTypes.hairColorChanger]: '/products/hair-color-changer',
  [moduleTypes.textToVideo]: '/products/ai-text-to-video-generator',
  [moduleTypes.photoFilterEffect]: '/products/photo-filter-effect',
  [moduleTypes.bodyReshape]: '/products/body-reshape',
  [moduleTypes.videoObjRemover]: '/products/video-object-remover',
  [moduleTypes.aiPhotoRepair]: '/products/ai-photo-repair',
  [moduleTypes.aiVideoEditor]: '/products/ai-video-editor',
  [moduleTypes.characterMotionSwap]: '/products/ai-motion-transfer',
  [moduleTypes.aiAgent]: '/ai-agent',
  [moduleTypes.aiAgentConnector]: '/products/ai-agent-connector',
  // Image Template's tool page moved under the shared "ai mix" product's
  // slug (/products/ai-photo-combiner/result-photo); Video Template's tool
  // page keeps its own path (/products/video-template/result-photo) — see
  // headerUtils.productUrl for the header-nav link override, since both
  // point at the same product/landing page (/products/ai-photo-combiner).
  [moduleTypes.imageTemplate]: '/products/ai-photo-combiner',
  [moduleTypes.videoTemplate]: '/products/video-template',
};

// URL fragments for video-input modules — derived from videoTypes4ModuleBanner + productUrls.
// Used to decide if the current page expects a video upload (e.g. <HiddenFileInput accept>).
// Single source of truth: to add a new video-input module, extend videoTypes4ModuleBanner;
// everything downstream picks it up automatically.
export const videoModuleUrlFragments = videoTypes4ModuleBanner
  .map((type) => productUrls[type])
  .filter(Boolean)
  .flatMap((url) => (typeof url === 'object' ? Object.values(url) : [url]));

// this config update on
// https://docs.google.com/spreadsheets/d/1q9KxAOy_II0MjPJXn8aAQAsc2n-TZHhCCTq7ormf3Jg/edit#gid=1520130144
export const headerProducts = {
  [moduleTypes.enhance]: 'photo-enhance',
  [moduleTypes.enhanceBatch]: 'photo-enhance-batch',
  [moduleTypes.objRemoval]: 'object-removal',
  [moduleTypes.removeBackground]: 'remove-background',
  [moduleTypes.blurBackground]: 'blur-background',
  [moduleTypes.changeBackground]: 'change-background',
  [moduleTypes.colorize]: 'colorize',
  [moduleTypes.avtV3Art]: 'avatar',
  [moduleTypes.avatar]: 'avatar',
  [moduleTypes.txt2Img]: 'ai-art-generator',
  [moduleTypes.hairStyle]: 'ai-hairstyle-generator',
  [moduleTypes.hairBang]: 'bangs-filter',
  [moduleTypes.hairExt]: 'before-and-after-hair-extensions',
  [moduleTypes.hairVol]: 'add-hair-to-photo-with-ai',
  [moduleTypes.hairWavy]: 'hair-wavy',
  [moduleTypes.aiApi]: 'ai-api',
  [moduleTypes.profilePictureMaker]: 'profile-pic-maker',
  [moduleTypes.aiFaceGenerator]: 'ai-face-generator',
  [moduleTypes.animeAiArtGenerator]: 'anime-ai-art-generator',
  [moduleTypes.cropPhoto]: 'crop-photo',
  [moduleTypes.resizeImage]: 'resize-image',
  [moduleTypes.oldPhotoRestoration]: 'old-photo-restoration',
  [moduleTypes.aiCharacterGenerator]: 'ai-character-generator',
  [moduleTypes.flipPhoto]: 'flip-photo',
  [moduleTypes.rotatePhoto]: 'rotate-photo',
  [moduleTypes.flipAndRotateImage]: 'flip-and-rotate-image',
  [moduleTypes.lighting]: 'lighting',
  [moduleTypes.outPaint]: 'out-paint',
  [moduleTypes.passportPhotoMaker]: 'passport-photo-maker',
  [moduleTypes.aiGirlGenerator]: 'ai-girl-generator',
  [moduleTypes.aiArtWorkGenerator]: 'ai-artwork-generator',
  [moduleTypes.photoToCartoon]: 'photo-to-cartoon',
  [moduleTypes.objReplace]: 'obj-replace',
  [moduleTypes.avtV3Img]: 'ai-portrait-generator',
  [moduleTypes.headshot]: 'ai-headshot-generator',
  [moduleTypes.muTransfer]: 'facial-makeup-transfer-filter',
  [moduleTypes.colorCorrection]: 'color-correction',
  [moduleTypes.videoSr]: 'video-enhancer-ai',
  [moduleTypes.faceShapeDetector]: 'face-shape-detector',
  [moduleTypes.faceSwap]: 'face-swap',
  [moduleTypes.dehazePhoto]: 'dehaze-photo',
  [moduleTypes.shaprenImage]: 'sharpen-image',
  [moduleTypes.unblurImage]: 'unblur-image',
  [moduleTypes.watermarkRemover]: 'watermark-remover',
  [moduleTypes.aiVideoFilters]: 'ai-video-filters',
  [moduleTypes.faceSwapVid]: 'video-face-swap',
  [moduleTypes.aiPortrait]: 'ai-portrait',
  [moduleTypes.img2Vid]: 'ai-video-generator',
  [moduleTypes.img2VidStd]: 'img-to-video-std',
  [moduleTypes.img2VidPro]: 'img-to-video-pro',
  [moduleTypes.viduVidTmpl]: 'vidu-vid-tmpl',
  [moduleTypes.makeup]: 'ai-makeup',
  [moduleTypes.imageConverter]: 'image-converter',
  [moduleTypes.imageConverterBatch]: 'image-converter-batch',
  [moduleTypes.adjustLightColor]: 'adjust-light-n-color',
  [moduleTypes.skinAnalysis]: 'ai-skin-analysis',
  [moduleTypes.faceReshape]: 'face-reshape',
  [moduleTypes.faceRetouch]: 'face-retouch',
  [moduleTypes.aiClothes]: 'ai-clothes',
  [moduleTypes.aiFabric]: 'ai-fabric',
  [moduleTypes.aiIllustrationGenerator]: 'ai-illustration-generator',
  [moduleTypes.aiGhibliFilter]: 'ai-ghibli-filter',
  [moduleTypes.aiImageUpscaler]: 'ai-image-upscaler',
  [moduleTypes.unpixelateImage]: 'unpixelate-image',
  [moduleTypes.aiImageEnlarger]: 'ai-image-enlarger',
  [moduleTypes.recolorImage]: 'recolor-image',
  [moduleTypes.removePeopleFromPhoto]: 'remove-people-from-photo',
  [moduleTypes.aiAnimateIllustration]: 'ai-animate-illustration',
  [moduleTypes.unblurVideo]: 'unblur-video',
  [moduleTypes.aiActionFigureGenerator]: 'ai-action-figure-generator',
  [moduleTypes.hairColor]: 'hair-color',
  [moduleTypes.removeGlareFromPhoto]: 'remove-glare-from-photo',
  [moduleTypes.skinToneAnalyzer]: 'skin-tone-analyzer',
  [moduleTypes.edit]: 'edit',
  [moduleTypes.beardFilter]: 'beard-filter',
  [moduleTypes.hairColorChanger]: 'hair-color-changer',
  [moduleTypes.hairType]: 'hair-type',
  [moduleTypes.hairLength]: 'hair-length',
  [moduleTypes.hairFrizziness]: 'hair-frizziness',
  [moduleTypes.facialRatio]: 'facial-ratio',
  [moduleTypes.skinToneAPI]: 'skin-tone',
  [moduleTypes.beardStyleAPI]: 'beard-style',
  [moduleTypes.faceAttributeAPI]: 'face-attribute',
  [moduleTypes.aiAgingAPI]: 'ai-aging',
  [moduleTypes.aiClothV2]: 'ai-cloth-v2',
  [moduleTypes.textToVideo]: 'ai-text-to-video-generator',
  [moduleTypes.photoFilterEffect]: 'photo-filter-effect',
  [moduleTypes.affiliates]: 'affiliates',
  [moduleTypes.aiMakeup]: 'makeup-virtual-try-ons',
  [moduleTypes.aiLook]: 'makeup-complete-looks-try-ons',
  [moduleTypes.contest]: 'contest',
  [moduleTypes.arRing]: 'makeup-ar-ring',
  [moduleTypes.arWatch]: 'makeup-ar-watch',
  [moduleTypes.arBracelet]: 'makeup-ar-bracelet',
  [moduleTypes.arEarrings]: 'makeup-ar-earrings',
  [moduleTypes.arNecklace]: 'makeup-ar-necklace',
  [moduleTypes.aiBag]: 'makeup-ai-bag',
  [moduleTypes.aiShoes]: 'makeup-ai-shoes',
  [moduleTypes.aiScarves]: 'makeup-ai-scarves',
  [moduleTypes.aiHat]: 'makeup-ai-hat',
  [moduleTypes.aiNail]: 'makeup-nail-try-ons',
  [moduleTypes.videoObjRemover]: 'video-object-remover',
  [moduleTypes.aiPhotoRepair]: 'ai-photo-repair',
  [moduleTypes.aiVideoEditor]: 'ai-video-editor',
  [moduleTypes.characterMotionSwap]: 'ai-motion-transfer',
  [moduleTypes.hairDensity]: 'hair-density',
  [moduleTypes.teethWhitening]: 'teeth-whitening',
  [moduleTypes.eyeColor]: 'eye-color',
  [moduleTypes.txt2ImgV2]: 'text-to-image-v2',
  [moduleTypes.img2VidV2API]: 'image-to-video-v2',
  [moduleTypes.hairStyleV1API]: 'ai-hairstyle-generator-v1-api',
  [moduleTypes.hairStyleV2API]: 'ai-hairstyle-generator-v2-api',
  [moduleTypes.skinSimulationAPI]: 'skin-simulation-api',
  [moduleTypes.breastSimulatorAPI]: 'breast-simulator-api',
  [moduleTypes.bodyReshapeAPI]: 'body-reshape-api',
  [moduleTypes.bodyReshape]: 'body-reshape',
  [moduleTypes.aiAgent]: 'ai-agent',
  [moduleTypes.aiAgentConnector]: 'ai-agent-connector',
  [moduleTypes.imageTemplate]: 'ai-photo-combiner',
  [moduleTypes.videoTemplate]: 'video-template',
};

export const headerCategoryTitles = {
  'header.items.product.group.ai.photo.editing': 'ai-photo-editing',
  'header.items.product.group.ai.portrait': 'ai-portrait',
  'header.items.product.group.ai.video.editing': 'ai-video-editing',
  // No dedicated template icon asset exists yet — reuses generative-ai's icon.
  'header.items.product.group.template': 'generative-ai',
};
